<?php
/***************************************************************************
	@extension	: Dealer Inquiry Extension.
	@copyright	: Copyright (c) 2014 Capacity Web Solutions.
	( http://www.capacitywebsolutions.com )
	@author		: Capacity Web Solutions Pvt. Ltd.
	@support	: magento@capacitywebsolutions.com	
***************************************************************************/

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <title></title>
</head>
<body>
	<div class="content-header">
		<table cellspacing="0">
			<tr>
				<td>
					<h3 class="head-dashboard">
						<?php echo $this->__('Dealer Inquiries') ?>
					</h3>
				</td>
			</tr>
		</table>
	</div>
	<?php $collections = ""; $collections = $this->getAllInquires(); ?>

	<div class="grid">
		<div class="hor-scroll">
			<table cellspacing="0" id="cmsPageGrid_table" class="data">
				<col width="10">
					<thead>
					<tr class="headings">
						<th>
							<span class="nobr"><a class="not-sort" title="asc" name="title">Sr#</a></span>
						</th>
						<th>
							<span class="nobr"><a class="not-sort" title="desc" name="identifier">First Name</a></span>
						</th>
						<th>
							<span class="nobr"><a class="not-sort" title="asc" name="root_template">Last Name</a></span>
						</th>
						<th>
							<span class="nobr"><a class="not-sort" title="asc" name="is_active">Company Name</a></span>
						</th>
						<th>
							<span class="nobr"><a class="not-sort" title="asc" name="creation_time">Email</a></span>
						</th>
						<th>
							<span class="nobr"><a class="not-sort" title="asc" name="update_time">Is Created</a></span>
						</th>
						<th>
							<span class="nobr"><a class="not-sort" title="asc" name="update_time">Created Date</a></span>
						</th>
						<th class=" no-link last">	
							<span class="nobr">Action</span>
						</th>
					</tr>
					</thead>
				<tbody>
				<?php
					if($collections->count() != "")
					{
				?>
				<?php 
					$i = 1;
					foreach($collections as $item)
					{
					    $website_id = Mage::getModel('core/store')->load($item['storeid'])->getWebsiteId();
  
						$IsCreated = $this->getIsCreated($item['email'],$website_id);
					?>
				<tr class="even pointer"> 
					<td class="" align="center"><?php echo $i;//$this->getIsCreated();?></td>
					<td class="a-left "><?php echo $item['firstname'];?></td>
					<td class="a-left "><?php echo $item['lastname'];?></td>
					<td class="a-left "><?php echo $item['company'];?></td>
					<td class="a-left "><?php echo $item['email'];?></td>
					<td class="a-left "><?php echo $IsCreated==0? "<font color='#FF0000'>Not Created</font>" : "<font color='#009933'>Created</font>";?></td>
					<td class="a-left "><?php echo date("F j, Y",strtotime($item['createddt']));?></td>
					<td class="a-left ">&nbsp;
						<a href="<?php echo $this->getUrl("inquiry/index/del/delid/".$item['dealerid'])?>" onclick="javascript:return confirm('Are  you sure to delete this Inquire?')"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."adminhtml/default/default/images/icon_btn_delete.gif";?>" alt="Delete" title="Delete" /></a>&nbsp;&nbsp;
           
						<a href="<?php echo Mage::helper("adminhtml")->getUrl("inquiry/adminhtml_inquiry/view/delid/".$item['dealerid']);?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."adminhtml/default/default/images/fam_page_white.gif";?>" alt="View" title="View" /></a>
  
						<?php if($IsCreated==0) {?>
						&nbsp;&nbsp;<a href="<?php echo Mage::helper("adminhtml")->getUrl("inquiry/adminhtml_inquiry/createCustomer/multival/".$item['email'].'~~'.$item['firstname'].'~~'.$item['lastname'].'~~'.$item['company'].'~~'.$item['address'].'~~'.$item['city'].'~~'.$item['state'].'~~'.$item['zip'].'~~'.$item['phone'].'~~'.$item['country'].'~~'.$item['taxvat'].'~~'.$item['storeid']);?>" onclick="javascript:return confirm('Are you sure  to create the account?')"><img src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."adminhtml/default/default/images/fam_page_white_edit.gif";?>" alt="Create Customer" title="Create Customer" /></a></td>
						<?php } ?>
				</tr>
				<?php  $i++;
				}
				}
				else
					echo "<tr><Td colspan='8' align='center'>No records found.</td></tr>";
				?>
				</tbody>
			</table>
		</div>
	</div>

</body>
</html>
