<?php

/***************************************************************************
	@extension	: Dealer Inquiry Extension.
	@copyright	: Copyright (c) 2014 Capacity Web Solutions.
	( http://www.capacitywebsolutions.com )
	@author		: Capacity Web Solutions Pvt. Ltd.
	@support	: magento@capacitywebsolutions.com	
***************************************************************************/

 $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat'); 
 $item = $this->getAllDealer($this->getRequest()->getParam("delid"));
 $website_id = Mage::getModel('core/store')->load($item['storeid'])->getWebsiteId();

 $IsCreated = $this->getIsCreated($item['email'],$website_id);

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <title></title>
</head>
<body>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__('Dealer Details') ?></h3></td>
        </tr>
    </table>
</div>
<?php		
	$prevurl = Mage::helper("adminhtml")->getUrl("inquiry/adminhtml_inquiry/index/"); ?>
	<div class="back">
		<a href="<?php echo $prevurl;?>">
			<span><font size="4px">&laquo;</font> Back</span>
		</a>&nbsp;&nbsp;
	<?php if($IsCreated==0) 
	{
	?> 
	&nbsp;&nbsp;<a href="<?php echo Mage::helper("adminhtml")->getUrl("inquiry/adminhtml_inquiry/createCustomer/multival/".$item['email'].'~~'.$item['firstname'].'~~'.$item['lastname'].'~~'.$item['company'].'~~'.$item['address'].'~~'.$item['city'].'~~'.$item['state'].'~~'.$item['zip'].'~~'.$item['phone'].'~~'.$item['country'].'~~'.$item['taxvat'].'~~'.$item['storeid']);?>" onclick="javascript:return confirm('Are you sure  to create the account?')">Create Customer</a>
	<?php 
	} 
	$country1 = explode('$$$',$item['country']);
	?>
	</div>
	<div class="grid">
		<div class="hor-scroll">
			<table cellspacing="0" id="cmsPageGrid_table" class="data">
			<col width="10">
			<thead>
				<tbody>
					<tr class="even pointer">
						<td class=""width="15%">First Name</td>
						<td class="a-left ">
							<?php echo $item['firstname'];?>
						</td>
					</tr>
					<tr class="even pointer">
						<td class=""width="15%">Last Name</td>
						<td class="a-left ">
							<?php echo $item['lastname'];?>
						</td>
					</tr>
                    <tr class="even pointer">
						<td class=""width="15%">Product For Enquiry</td>
						<td class="a-left ">
							<?php echo $item['productname'];?>
						</td>
					</tr>
                    <tr class="even pointer">
						<td class=""width="15%">SKU</td>
						<td class="a-left ">
							<?php echo $item['sku'];?>
						</td>
					</tr>
					<tr class="even pointer">
						<td class=""width="15%">Company Name</td>
						<td class="a-left ">
							<?php echo $item['company'];?>
						</td>
					</tr>
				
					<tr class="even pointer">
						<td class=""width="15%">Tax/VAT Number</td>
						<td class="a-left ">
							<?php if($item['taxvat']==""): echo "-";else:echo $item['taxvat'];endif;?>
						</td>
					</tr>
				
					 <tr class="even pointer">
						<td class=""width="15%">Address</td>
						<td class="a-left "><?php echo $item['address'];?></td>
					</tr>
					<tr class="even pointer">
						<td class=""width="15%">City</td>
						<td class="a-left "><?php echo $item['city'];?></td>
					</tr>
					<tr class="even pointer">
						<td class=""width="15%">State</td>
						<td class="a-left "><?php echo $item['state'];?></td>
					</tr>
					<tr class="even pointer">
						<td class=""width="15%">Country</td>
						<td class="a-left "><?php echo $country1[1];?></td>
					</tr>
					<tr class="even pointer">
						<td class=""width="15%">Zip</td>
						<td class="a-left "><?php echo $item['zip'];?></td>
					</tr>
					<tr class="even pointer">
						<td class=""width="15%">Phone</td>
						<td class="a-left "><?php echo $item['phone'];?></td>
					</tr>
					<tr class="even pointer">
						<td class=""width="15%">Email</td>
						<td class="a-left "><?php echo $item['email'];?></td>
					</tr>
                    <tr class="even pointer">
                        <td class=""width="15%">Interested in</td>
                        <td class="a-left "><?php echo $item['categories'];?></td>
                    </tr>
					<tr class="even pointer">
						<td class=""width="15%">Website</td>
						<td class="a-left "><?php if($item['website']==""): echo "-";else:echo $item['website'];endif; ?></td>
					</tr>
					<tr class="even pointer">
						<td class=""width="15%">Is Created</td>
						<td class="a-left "><?php echo $IsCreated==0? "<font color='#FF0000'>Not Created</font>" : "<font color='#009933'>Created</font>";?></td>
					</tr>
					<tr class="even pointer">
						<td class=""width="15%">Created Date</td>
						<td class="a-left "><?php echo date("F j, Y",strtotime($item['createddt']));?></td>
					</tr>
					<tr class="even pointer">
						<td class=""width="15%">Business Description</td>
						<td class="a-left "><p><?php if($item['desc']==""): echo "-"; else:echo stripslashes($item['desc']);endif;?></p></td>
					</tr>
				</tr>
			</tbody>
		</table>
   	</div>
</div>

</body>
</html>
