<?php
/***************************************************************************
	@extension	: Dealer Inquiry Extension.
	@copyright	: Copyright (c) 2014 Capacity Web Solutions.
	( http://www.capacitywebsolutions.com )
	@author		: Capacity Web Solutions Pvt. Ltd.
	@support	: magento@capacitywebsolutions.com	
***************************************************************************/

 $code =  trim($this->getRandomCode()); 
 $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat'); 
 $heading = trim(Mage::getStoreConfig('inquiry/general/heading'));
 $indicates = trim(Mage::getStoreConfig('inquiry/general/indicates'));
 $des_gen = trim(Mage::getStoreConfig('inquiry/general/description'));
 $btn_text = trim(Mage::getStoreConfig('inquiry/general/btn_text'));
 $first_name = trim(Mage::getStoreConfig('inquiry/change_label/f_name'));
 $last_name = trim(Mage::getStoreConfig('inquiry/change_label/l_name')); 
 $company_name = trim(Mage::getStoreConfig('inquiry/change_label/company_name')); 
 $vat_number = trim(Mage::getStoreConfig('inquiry/change_label/vat_number')); 
 $address = trim(Mage::getStoreConfig('inquiry/change_label/address')); 
 $city = trim(Mage::getStoreConfig('inquiry/change_label/city')); 
 $state = trim(Mage::getStoreConfig('inquiry/change_label/state')); 
 $country = trim(Mage::getStoreConfig('inquiry/change_label/country')); 
 $postal_code = trim(Mage::getStoreConfig('inquiry/change_label/postal_code')); 
 $contact_number = trim(Mage::getStoreConfig('inquiry/change_label/contact_number')); 
 $email = trim(Mage::getStoreConfig('inquiry/change_label/email')); 
 $website = trim(Mage::getStoreConfig('inquiry/change_label/website'));
 $description = trim(Mage::getStoreConfig('inquiry/change_label/description')); 
 $last_name_hide = Mage::getStoreConfig('inquiry/label_hide/l_name');  
 $vat_number_hide = Mage::getStoreConfig('inquiry/label_hide/vat_number'); 
 $address_hide = Mage::getStoreConfig('inquiry/label_hide/address'); 
 $city_hide = Mage::getStoreConfig('inquiry/label_hide/city'); 
 $state_hide = Mage::getStoreConfig('inquiry/label_hide/state'); 
 $country_hide = Mage::getStoreConfig('inquiry/label_hide/country'); 
 $postal_code_hide = Mage::getStoreConfig('inquiry/label_hide/postal_code'); 
 $website_hide = Mage::getStoreConfig('inquiry/label_hide/website');
 $captcha_hide = Mage::getStoreConfig('inquiry/label_hide/captcha');

 ?>

<?php if($captcha_hide): ?>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'inquiry/jquery.min.js'?>">
</script>
<script>
var jq = $.noConflict();
jq(document).ready(function(){
jq("#img_refresh").click(function(){
   jq("#captcha").load(location.href + " #captcha");
	});
});
</script>
<script language="JavaScript" type="text/JavaScript">
    function captchacode()
    {
		var captcha = document.getElementById('capt').value;
		var captcha_code = document.getElementById('captcha_code').value;
		if (captcha == "")
		{
			return true;
		}
		if (captcha==captcha_code)
		{
			return true;
		}
		else
		{
			alert ("captcha code does not match!");
			return false;
		}
	}
</script>
<?php endif; ?>

<div id="about-copy" class="inquiryForm">
	<h1><img src="<?php echo $this->getSkinUrl('images/inquiry-icon.png') ?>" alt="" /><?php if($heading): ?><?php echo $this->__($heading); ?><?php endif; ?></h1>
	<p><?php if($des_gen): ?><?php echo $des_gen; ?><?php endif; ?></p>
    <?php if($indicates != "") { ?>
		<div class="indicates"><span class="required"><em>*</em></span><?php echo $this->__($indicates); ?></div>
	<?php } ?>
	
	<?php 
		$msg = Mage::getSingleton('core/session')->getSomeSessionVar();
	    if($msg == 'wrong') { ?>
			<div id="messages">
				<ul class="messages">
					<li class="error-msg">
						<ul><li>
							<span style="font-size:12px;">captcha code does not match!</span>
						</li></ul>
					</li>
				</ul>
			</div>
	<?php Mage::getSingleton('core/session')->unsSomeSessionVar();
	      $msg = '';  } ?>
	<?php 
		$msgs = Mage::getSingleton('core/session')->getSomeSessionVar();
	    if($msgs == 'email_wrong') { ?>
			<div id="messages">
				<ul class="messages">
					<li class="error-msg">
						<ul><li>
							<span style="font-size:12px;">Email id already exits !</span>
						</li></ul>
					</li>
				</ul>
			</div>
	<?php Mage::getSingleton('core/session')->unsSomeSessionVar();
	      $msg = '';  } ?>	  

    <form name="dealerInquiry" id="dealerInquiry" action="<?php echo $this->getUrl("inquiry/index/thanks"); ?>" method="post">
    	<div class="fieldset">
        	<ul class="form-list">
            	<li class="fields">
                	<div class="field">
						<label><?php if($first_name): ?><?php echo $first_name; ?><?php else: ?><?php echo "First Name:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="fname" id="fname" size="45" class="input-text required-entry input-box" />
                        </div>
                    </div>
                    <?php if($last_name_hide): ?> 
                    <div class="field">
                    	<label><?php if($last_name): ?><?php echo $last_name; ?><?php else: ?><?php echo "Last Name:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="lname" size="45" class="input-text required-entry" />
                        </div>
                    </div>
                    <?php endif;  ?>
                </li>
                <li class="fields">
                	<div class="field">
                    	<label><?php if($company_name): ?><?php echo $company_name; ?><?php else: ?><?php echo "Company Name:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="company" size="45" class="input-text required-entry" />
                        </div>
                    </div>
				
					<?php if($vat_number_hide): ?>
                    <div class="field">
                    	<label><?php if($vat_number): ?><?php echo $vat_number; ?><?php else: ?><?php echo "Tax/VAT Number:"; ?><?php endif;  ?></label>
                        <div class="input-box">
                        	<input type="text" name="account_taxvat" size="45" class="input-text" /> 
                        </div>
                    </div>
                    <?php endif; ?>
					
					
					
                    <?php if($address_hide): ?>  
                	<div class="field">
                    	<label><?php if($address): ?><?php echo $address; ?> <?php else: ?><?php echo "Address:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
	                        <textarea name="address" cols="42" rows="1" class="input-text required-entry"></textarea>
                        </div>
                    </div>
                    <?php endif; ?>
                </li>
                <li class="fields">
                    <?php if($city_hide): ?>
                    <div class="field">
                    	<label><?php if($city): ?><?php echo $city; ?><?php else: ?><?php echo "City:"; ?><?php endif;  ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="city" size="45" class="input-text required-entry" /> 
                        </div>
                    </div>
                    <?php endif; ?>
                    <?php if($state_hide): ?>
                	 <div class="field">
                     	<label><?php if($state): ?><?php echo $state; ?><?php else: ?><?php echo "State / Province:"; ?><?php endif;  ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
	                        <input type="text" name="state_id" size="45" class="input-text required-entry" />
                        </div>
                     </div>
                     <?php endif; ?>
                </li>
                <li class="fields">
                     <?php if($country_hide): ?>
                     <div class="field">
                     	<label><?php if($country): ?><?php echo $country; ?><?php else: ?><?php echo "Country:"; ?><?php endif;  ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                            <select name="country" id="country" class="drop" class="input-text required-entry">
                                <?php
                                    $countryCode = Mage::getStoreConfig('general/country/default');
                                    $country_name=Mage::app()->getLocale()->getCountryTranslation($countryCode);
                                    $collection = Mage::getModel('directory/country')->getCollection();
                                    foreach ($collection as $country)
                                    {
                                    $cid = $country->getId();
                                    $cname = $country->getName(); 
                                ?>
                                    <option value="<?php echo $cid.'$$$'.$cname; ?>"<?php if($cid == $countryCode) echo "SELECTED" ?> ><?php echo $cname; ?></option>
                                <?php 
                                } 
                                ?>
                            </select>
                        </div>
                     </div>
                     <?php endif; ?>
                     <?php if($postal_code_hide): ?>
                  	 <div class="field">
                    	<label><?php if($postal_code): ?><?php echo $postal_code; ?><?php else: ?><?php echo "ZIP / Postal Code:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                 			<input type="text" name="zip" id="zip" size="45" maxlength="10" class="required-entry input-text required-entry input-text required-entry validation-passed" />
                        </div>
                     </div>
                    <?php endif; ?>
                </li>
                <li class="fields">
                    <div class="field">
                    	<label><?php if($contact_number): ?><?php echo $contact_number; ?><?php else: ?><?php echo "Contact Number:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
                        <div class="input-box">
                        	<input type="text" name="phone" size="45" onKeyPress="return isNumberKey(event)" maxlength="15" class="input-text validate input-text required-entry"/>
                        </div>
                    </div>
				</li>
				 <li class="fields">
                    <div class="field">
	                	<label><?php if($email): ?><?php echo $email; ?><?php else: ?><?php echo "Email:"; ?><?php endif; ?><span class="required"><em>*</em></span></label>
    	            	<div class="input-box">
                        	<input type="text" name="email" size="45" class="input-text validate-email required-entry" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <?php if($website_hide): ?>
                    <div class="field">
                    	<label><?php if($website): ?><?php echo $website; ?><?php else: ?><?php echo "Website:"; ?><?php endif; ?></label>
                        <div class="input-box">
                        	<input type="text" name="website" size="45" class="input-text" /> 
                        </div>
                    </div>
                    <?php endif; ?>
                    <div class="field">
                        <label><?php if($description): ?><?php echo $description; ?><?php else: ?><?php echo "Business Description:"; ?><?php endif; ?></label>
                        <div class="input-box">
                            <textarea name="bdesc" cols="75" rows="2" class="input-text"></textarea>
                        </div>
                    </div>
                </li>
                <li class="fields last">
				<?php if($captcha_hide): ?>  
                	<label>Capctha<span class="required"><em>*</em></span></label>
                    <div class="captcha-main">
                        <div id="captcha" class="captcha-left">
                            <b><?php echo $code; ?></b>&nbsp; 
                            <input type="hidden" value="<?php echo $code; ?>" id="captcha_code" size="45" name="captcha_code">
                        </div> 
                    </div> 
                    <div id="img_refresh"><img src="<?php echo $this->getSkinUrl('images/refresh.png') ?>"></div>
                    <div class="clear"></div>
                    <input type="text" name="captcha" id="capt" size="24" value="" class="input-text required-entry" />
                <?php endif; ?>
                </li>
        	</ul>
            <div class="clear"></div>
            <div class="button-set">
					<button type="submit" name="SUBMIT"  class="button" value="SUBMIT" onclick="return captchacode() ;"><span><span><?php if($btn_text): ?><?php echo $btn_text; ?><?php else: ?><?php echo "Submit"; ?><?php endif;  ?></span></span></button>
            </div>
        </div>
    </form>
    <div class="clear"></div>
</div>
<script type="text/javascript">
//< ![CDATA[
var customForm = new VarienForm('dealerInquiry');
//]]>
	function isNumberKey(evt)
	{
		 var charCode = (evt.which) ? evt.which : evt.keyCode
		 if (charCode > 31 && (charCode < 48 || charCode > 57))
		 {
		 	return false;
		}		
		 return true;
	} 

</script>
