<?php
/***************************************************************************
@extension	: Dealer Inquiry Extension.
@copyright	: Copyright (c) 2014 Capacity Web Solutions.
( http://www.capacitywebsolutions.com )
@author		: Capacity Web Solutions Pvt. Ltd.
@support	: magento@capacitywebsolutions.com
 ***************************************************************************/
?>


<?php
$success_tital = Mage::getStoreConfig('inquiry/general/success_tital');
$success_des = Mage::getStoreConfig('inquiry/general/success_des');
?>

<div id="about-copy" class="inquiryThank">
    <h1><?php if($success_tital): ?><?php echo $success_tital; ?><?php endif; ?></h1>
    <p>
        <?php if($success_des): ?>
            <?php echo $success_des; ?>
        <?php endif;  ?>
    </p>
</div>